'use client'
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { AuthProvider, useAuth } from "../../context/AuthContext";
import Sidebar from "../pages/SideBar/SideBar"; // Import the Sidebar component
import { Inter } from "next/font/google";

const inter = Inter({
  subsets: ["latin"],
  variable: "--font-inter",
});

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

// export const metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

function Layout({ children }) {
  const { isAuthenticated } = useAuth();

  if (!isAuthenticated) {
    // Render only the login component without Sidebar or layout
    return <>{children}</>;
  }

  // Render the layout with Sidebar and main content
  return (
    <div className="flex h-screen">
      <Sidebar /> {/* Sidebar on the left */}
      <main className="flex-1 bg-gray-100 p-6 overflow-y-auto">
        {children} {/* Main content */}
      </main>
    </div>
  );
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} ${inter.variable} antialiased`}
      >
        <AuthProvider>
          <Layout>{children}</Layout>
        </AuthProvider>
      </body>
    </html>
  );
}
